// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARpJ5eloVosBBgBfLhMx1NIlG6GGEHN2o',
    appId: '1:903214282834:web:42b73afa550c86c90ac78b',
    messagingSenderId: '903214282834',
    projectId: 'sponti-44aa0',
    authDomain: 'sponti-44aa0.firebaseapp.com',
    storageBucket: 'sponti-44aa0.firebasestorage.app',
    measurementId: 'G-BK39QR82L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnaASc9l6Va37-4GM-AIMevlpqt8rVIrw',
    appId: '1:903214282834:android:9b1ad93eadec81970ac78b',
    messagingSenderId: '903214282834',
    projectId: 'sponti-44aa0',
    storageBucket: 'sponti-44aa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD73VIuAx5CWjsFnuLWdSUqHcrdJPYow_E',
    appId: '1:903214282834:ios:0facf902a4fd2dfe0ac78b',
    messagingSenderId: '903214282834',
    projectId: 'sponti-44aa0',
    storageBucket: 'sponti-44aa0.firebasestorage.app',
    iosBundleId: 'com.sponti.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARpJ5eloVosBBgBfLhMx1NIlG6GGEHN2o',
    appId: '1:903214282834:web:867cdf94603f88990ac78b',
    messagingSenderId: '903214282834',
    projectId: 'sponti-44aa0',
    authDomain: 'sponti-44aa0.firebaseapp.com',
    storageBucket: 'sponti-44aa0.firebasestorage.app',
    measurementId: 'G-X2JWTEZ552',
  );
}
